/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_zjy_patchupdate_BsPatch */

#ifndef _Included_cn_zjy_patchupdate_BsPatch
#define _Included_cn_zjy_patchupdate_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_zjy_patchupdate_BsPatch
 * Method:    merge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_zjy_patchupdate_BsPatch_merge
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
