/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_zjy_patchupdate_PatchUpdate */

#ifndef _Included_cn_zjy_patchupdate_PatchUpdate
#define _Included_cn_zjy_patchupdate_PatchUpdate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_zjy_patchupdate_PatchUpdate
 * Method:    mergePatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_cn_zjy_patchupdate_PatchUpdate_mergePatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
